### ISSUE TITLE
Revisar issues da primeira iteração: quebrar em mais atividades

### ISSUE THREAD

**Issue by DanielDantasL** [ES2-UFPI/QuizMania#6]

**Comment by carlosdac** [comment]
Bom pessoal, nessa primeira issue, de cara vejo que ela pode ser quebrada em pelo menos duas outras issue: Criar endpoint de responder quiz e criar tela para responder quiz

**Comment by carlosdac** [comment]
Acredito que devemos criar issues para realizarmos a criação do projeto base e enviarmos também

**Comment by DanielDantasL** [comment]
Atividades discutidas e destrinchadas.
